### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by danieldietrich** [rocketscience-projects/javaslang#118]
1. Update github readme ✓
2. Deploy javaslang-1.2.0 to Maven Central ✓
3. Update http://javaslang.com ✓

**Comment by danieldietrich** [comment]
Random thoughts:

* Beware of releasing the local version of the Javaslang repo to maven central. Uncommitted changes will be also published. Instead check out a fresh copy from github and deploy it to maven central.

**Comment by talios** [comment]
Er, not if you're using the maven-release-plugin as it tags during the `prepare` and checks out a local copy during the `perform` stages.

We tend to use the following configuration at work however:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>2.5</version>
        <configuration>
            <preparationGoals>clean install</preparationGoals>
            <goals>deploy</goals>
            <pushChanges>false</pushChanges>
            <localCheckout>true</localCheckout>
        </configuration>
    </plugin>

This tells the release plugin to not do a `git push` during prepare, and to do a local checkout, this is useful if you're using a release branch or need to re-roll a release that didn't quite work, saves having messy published commits/tags.

The release plugin already checks for uncommitted files, but doesn't know anything about un-added files ( the local checkout / test install however traps that ).

**Comment by danieldietrich** [comment]
Thanks, that helps! I'm not up-to-date regarding releasing with git - at work we still use svn o_O :-)

**Comment by danieldietrich** [comment]
After this release move to pull requests instead of direct commits to

* enable code reviews
* maintain 100% code coverage & javadoc
* get a change log between releases
* move to a feature driven development instead of committing unrelated technical changes

**Comment by danieldietrich** [comment]
Create a simple illustration of the collection API on javaslang.com. Example: https://twitter.com/hyPiRion/status/583680829945163776/photo/1
