### ISSUE TITLE
Add Try.andThen

### ISSUE THREAD

**Issue by danieldietrich** [rocketscience-projects/javaslang#129]
... to support chaining of side effects like

```java
Try.run(server::start).andThen(server::join);
```

**Comment by ggalmazor** [comment]
Maybe we could also benefit from something like Try.peek() (as in Stream.peek()) to support side effects on a map/filter pipeline. This would be helpful with objects like the one from your example whose methods don't return themselves (impeding their use on map() phases in the pipeline).

**Comment by danieldietrich** [comment]
yes, had that idea also for Traversable - will check how it integrates
