### ISSUE TITLE
Unleash javaslang.Lazy

### ISSUE THREAD

**Issue by danieldietrich** [rocketscience-projects/javaslang#130]
Lazy is a memoizing Supplier and it is already used internally in Javaslang. It is useful, so let's make it public.

Lazy evaluation should be a first class citizen of a language, like functions and tuples. Therefore the right place is the first-level package of Javaslang.

Example:

```java
Supplier<Double> d = Lazy.of(Math::random)
d.get() // returns a random double, e.g. 0.123
d.get() // returns the memoized value, e.g. 0.123
```

**Comment by lukaseder** [comment]
Javaslang is getting more and more awesome. Time for a guest blog post? :-)

**Comment by danieldietrich** [comment]
Yes, I think it's time :-)
Thank you, Lukas.
This will take a few days (beside my daylight job)

**Comment by lukaseder** [comment]
Well, we're not in a hurry. It was just me, checking, periodically :)

**Comment by danieldietrich** [comment]
The Lukas-Eder-Bot ;-)

**Comment by lukaseder** [comment]
I wish I had one, seriously! :)

**Comment by danieldietrich** [comment]
:+1: I will file an issue on the jOOQ page :-)

What is the format of the blog post, e.g. for code snippets?

**Comment by danieldietrich** [comment]
Great!
