### ISSUE TITLE
Ideas for enhancements of Try

### ISSUE THREAD

**Issue by rocketscience-projects** [rocketscience-projects/javaslang#7]
[Repenser-la-propagation-des-exceptions-avec-Java-8](http://blog.zenika.com/index.php?post/2014/02/19/Repenser-la-propagation-des-exceptions-avec-Java-8)

**Comment by danieldietrich** [comment]
Making Option, Try et.al. more collection-like is out of focus.

**Comment by mperry** [comment]
I can't read French(?), but Try looks like the Validation class in FJ.  FJ uses Try, Try0, Try1, ... and TryEffect, TryEffect0, TryEffect1, etc. for lambdas that can throw an exception and then returns either void or A respectively.

The Try series have type signatures for function application like `A f() throws Z`, whereas TryEffect0 has a void return `void f() throws Z`.  We then convert this to a P1 or function that returns a `Validation<Z, Unit>` (for arity 0) and treat it like any other value.

**Comment by danieldietrich** [comment]
Yes, I've seen fj's Validation class. It's a good way for pure functional programming. The Javaslang world takes a simpler appoach by the cost of impurity. Java's well known try/catch

```java
try {
   bunchOfWork();
} catch(Exception_1 x) {
   ...
} catch(Exception_2 x) {
   ...
} catch(Exception_n x) {
   ...
}
```

is replaced by using Javaslang's Try Monad:

```java
Try(this::bunchOfWork).recover(x -> ...).getOrElse(other);
```

Maybe in conjunction with the Match API, where Try and Match can be seen as expressions:

```java
Try(this::bunchOfWork).recover(x -> Matchs
        .caze((Exception_1 x) -> ...)
        .caze((Exception_2 x) -> ...)
        .caze((Exception_n x) -> ...)
}).getOrElse(other);
```

That's the way Javaslang works. I do not plan to introduce more Try types.

**Comment by danieldietrich** [comment]
Oh, realized that we have done very similar things. Your `Validation` is mine `Try` and your `Try``s are the checked functions.
