### ISSUE TITLE
Rename Lambda.λ* to Function.Function*

### ISSUE THREAD

**Issue by danieldietrich** [rocketscience-projects/javaslang#83]
**Pro:**

* λ is hard to type
* The lower case letter λ is not conform to Java naming conventions (it should be Λ for a type)
* Function0..Function13 is a convenient addition to the existing java.util.Function type

**Con:**

* Long (generic) type definitions, i.e. curried versions, are hard to read

**Note:**

It is no problem that `javaslang.Function` overlaps with `java.util.Function`. Javaslang uses interfaces as modules to keep the number of packages and also the number of types within packages as tight as possible. Instead of using

```java
import javaslang.Function;
// ...
Function.Function0 fun;
```

It is highly recommended to use

```java
import javaslang.Function.*;
// ...
Function0 fun;
```

Your favorite IDE problably assists you importing inner types.

By the way, most types of Javaslang are modules in the sense described above.

**Comment by lukaseder** [comment]
Hehe, you actually use `λ` in your code? That's awesome! You should leave it in some places (e.g. static methods) as an alias for the alternative representation :)

**Comment by danieldietrich** [comment]
Hi Lukas, just found you comment - my inbox explodes because of my own activity :-)
Yes, good idea - I thought of sth similar months ago but forgot about it.
Good to know you have an eye!!
